# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.AutoField(db_column='circuitId', primary_key=True, serialize=False)),
                ('circuitref', models.CharField(db_column='circuitRef', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'circuits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructorResults',
            fields=[
                ('constructorresultsid', models.AutoField(db_column='constructorResultsId', primary_key=True, serialize=False)),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'constructorResults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.AutoField(db_column='constructorId', primary_key=True, serialize=False)),
                ('constructorref', models.CharField(db_column='constructorRef', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'constructors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('constructorstandingsid', models.AutoField(db_column='constructorStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'constructorStandings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.AutoField(db_column='driverId', primary_key=True, serialize=False)),
                ('driverref', models.CharField(db_column='driverRef', max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('driverstandingsid', models.AutoField(db_column='driverStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'driverStandings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lapTimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitstops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitStops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.AutoField(db_column='qualifyId', primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qualifying',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.AutoField(db_column='raceId', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitid', models.IntegerField(db_column='circuitId')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'races',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.AutoField(db_column='resultId', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(db_column='positionText', max_length=255)),
                ('positionorder', models.IntegerField(db_column='positionOrder')),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, db_column='fastestLap', null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestlaptime', models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True)),
                ('fastestlapspeed', models.CharField(blank=True, db_column='fastestLapSpeed', max_length=255, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(db_column='statusId', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CircuitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=255)),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Circuits')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=255)),
                ('constructorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Constructors')),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=255)),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Drivers')),
            ],
        ),
    ]
