# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStats',
            fields=[
                ('driverid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstletter', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=3)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('forenamerus', models.CharField(max_length=255)),
                ('surnamerus', models.CharField(max_length=255)),
                ('nationalityrus', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('podium', models.IntegerField(blank=True, null=True)),
                ('pole', models.IntegerField(blank=True, null=True)),
                ('bestfinish', models.IntegerField(blank=True, null=True)),
                ('beststart', models.IntegerField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('fl', models.IntegerField(blank=True, null=True)),
                ('lapsled', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('pointsgraph', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'driverstats',
                'managed': False,
            },
        ),
    ]
