# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_driverstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitdetail',
            name='driverid',
        ),
        migrations.RemoveField(
            model_name='constructordetail',
            name='constructorid',
        ),
        migrations.RemoveField(
            model_name='driverdetail',
            name='driverid',
        ),
        migrations.DeleteModel(
            name='CircuitDetail',
        ),
        migrations.DeleteModel(
            name='ConstructorDetail',
        ),
        migrations.DeleteModel(
            name='DriverDetail',
        ),
    ]
