# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('races', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('lapst', models.IntegerField()),
                ('lapsf', models.IntegerField()),
                ('lapsl', models.IntegerField()),
                ('champion', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('bestq', models.IntegerField()),
                ('bestr', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('races', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('lapst', models.IntegerField()),
                ('lapsf', models.IntegerField()),
                ('lapsl', models.IntegerField()),
                ('champion', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('bestq', models.IntegerField()),
                ('bestr', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
