# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Drivers')),
            ],
        ),
    ]
